language: java
jdk: oraclejdk8
sudo: false
services:
  - postgresql

addons :
  postgresql : " 9.4"
  postgres:
    adapter: postgresql
    database: travis_ci_test
    username: postgres
    password: 123

branches:
  only:
    - master

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: true
cache:
  directories:
  - $HOME/.m2
script: mvn clean install